name 'ianunruh-multi_http'
author 'Ian Unruh'
version '0.1.1'
source 'git://github.com/ianunruh/puppet-multi-http.git'
license 'MIT'
summary 'Puppet report handler that supports multiple HTTP urls'
description 'Puppet report handler that supports multiple HTTP urls'
project_page 'https://github.com/ianunruh/puppet-multi-http'
